# ========================================
# CONFIGURACIÓN DEL DEPARTAMENTO DE VOTACIÓN
# ========================================

# Identificación del departamento
nodo.id=DEPARTAMENTO-002
nodo.nombre=Departamento Central

# Configuración del servidor Ice (para recibir del broker lugar-departamento)
departamento.host=10.147.19.37
departamento.puerto=57713
departamento.timeout=5000

# Configuración del servidor central (conexión directa - sin broker)
servidor.central.host=10.147.19.39
servidor.central.puerto=57713
servidor.central.timeout=5000

# Configuración de deltas
delta.umbral.votos=2000        
# Enviar cada 2000 votos consolidados
delta.umbral.tiempo=3000       
# O cada 3 segundos (en ms)

# Thread Pool para Map-Reduce
threads.pool.size=12            
# Hilos para MAP phase

# Configuración de conexión
conexion.reintentos=3
conexion.timeout=3000

# Configuración de logging
logging.nivel=INFO
logging.archivo=departamento.log