//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VotingService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingSystem;

public class Candidato extends com.zeroc.Ice.Value
{
    public Candidato()
    {
        this.cedula = "";
        this.nombre = "";
        this.apellido = "";
        this.partidoPolitico = "";
    }

    public Candidato(String cedula, String nombre, String apellido, String partidoPolitico)
    {
        this.cedula = cedula;
        this.nombre = nombre;
        this.apellido = apellido;
        this.partidoPolitico = partidoPolitico;
    }

    public String cedula;

    public String nombre;

    public String apellido;

    public String partidoPolitico;

    public Candidato clone()
    {
        return (Candidato)super.clone();
    }

    public static String ice_staticId()
    {
        return "::VotingSystem::Candidato";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = 1317684845L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeString(cedula);
        ostr_.writeString(nombre);
        ostr_.writeString(apellido);
        ostr_.writeString(partidoPolitico);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        cedula = istr_.readString();
        nombre = istr_.readString();
        apellido = istr_.readString();
        partidoPolitico = istr_.readString();
        istr_.endSlice();
    }
}
