//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VotingService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingSystem;

public class Ciudadano extends com.zeroc.Ice.Value
{
    public Ciudadano()
    {
        this.documento = "";
        this.nombre = "";
        this.apellido = "";
        this.mesaId = "";
    }

    public Ciudadano(int id, String documento, String nombre, String apellido, String mesaId, boolean yaVoto)
    {
        this.id = id;
        this.documento = documento;
        this.nombre = nombre;
        this.apellido = apellido;
        this.mesaId = mesaId;
        this.yaVoto = yaVoto;
    }

    public int id;

    public String documento;

    public String nombre;

    public String apellido;

    public String mesaId;

    public boolean yaVoto;

    public Ciudadano clone()
    {
        return (Ciudadano)super.clone();
    }

    public static String ice_staticId()
    {
        return "::VotingSystem::Ciudadano";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = -1204416120L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeInt(id);
        ostr_.writeString(documento);
        ostr_.writeString(nombre);
        ostr_.writeString(apellido);
        ostr_.writeString(mesaId);
        ostr_.writeBool(yaVoto);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        id = istr_.readInt();
        documento = istr_.readString();
        nombre = istr_.readString();
        apellido = istr_.readString();
        mesaId = istr_.readString();
        yaVoto = istr_.readBool();
        istr_.endSlice();
    }
}
