//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VotingService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingSystem;

public class ConsultaLugarResponse extends com.zeroc.Ice.Value
{
    public ConsultaLugarResponse()
    {
        this.departamento = "";
        this.ciudad = "";
        this.lugarNombre = "";
        this.direccion = "";
        this.mesaId = "";
        this.mensaje = "";
    }

    public ConsultaLugarResponse(String departamento, String ciudad, String lugarNombre, String direccion, String mesaId, boolean encontrado, String mensaje)
    {
        this.departamento = departamento;
        this.ciudad = ciudad;
        this.lugarNombre = lugarNombre;
        this.direccion = direccion;
        this.mesaId = mesaId;
        this.encontrado = encontrado;
        this.mensaje = mensaje;
    }

    public String departamento;

    public String ciudad;

    public String lugarNombre;

    public String direccion;

    public String mesaId;

    public boolean encontrado;

    public String mensaje;

    public ConsultaLugarResponse clone()
    {
        return (ConsultaLugarResponse)super.clone();
    }

    public static String ice_staticId()
    {
        return "::VotingSystem::ConsultaLugarResponse";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = -45188202L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeString(departamento);
        ostr_.writeString(ciudad);
        ostr_.writeString(lugarNombre);
        ostr_.writeString(direccion);
        ostr_.writeString(mesaId);
        ostr_.writeBool(encontrado);
        ostr_.writeString(mensaje);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        departamento = istr_.readString();
        ciudad = istr_.readString();
        lugarNombre = istr_.readString();
        direccion = istr_.readString();
        mesaId = istr_.readString();
        encontrado = istr_.readBool();
        mensaje = istr_.readString();
        istr_.endSlice();
    }
}
