//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VotingService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingSystem;

public class Votante extends com.zeroc.Ice.Value
{
    public Votante()
    {
        this.cedula = "";
        this.nombre = "";
        this.apellido = "";
        this.departamento = "";
        this.ciudad = "";
    }

    public Votante(String cedula, String nombre, String apellido, String departamento, String ciudad, boolean yaVoto)
    {
        this.cedula = cedula;
        this.nombre = nombre;
        this.apellido = apellido;
        this.departamento = departamento;
        this.ciudad = ciudad;
        this.yaVoto = yaVoto;
    }

    public String cedula;

    public String nombre;

    public String apellido;

    public String departamento;

    public String ciudad;

    public boolean yaVoto;

    public Votante clone()
    {
        return (Votante)super.clone();
    }

    public static String ice_staticId()
    {
        return "::VotingSystem::Votante";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = -1719293679L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeString(cedula);
        ostr_.writeString(nombre);
        ostr_.writeString(apellido);
        ostr_.writeString(departamento);
        ostr_.writeString(ciudad);
        ostr_.writeBool(yaVoto);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        cedula = istr_.readString();
        nombre = istr_.readString();
        apellido = istr_.readString();
        departamento = istr_.readString();
        ciudad = istr_.readString();
        yaVoto = istr_.readBool();
        istr_.endSlice();
    }
}
