//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VotingService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingSystem;

public class Voto extends com.zeroc.Ice.Value
{
    public Voto()
    {
        this.votoId = "";
        this.timestamp = "";
    }

    public Voto(String votoId, Candidato candidato, String timestamp)
    {
        this.votoId = votoId;
        this.candidato = candidato;
        this.timestamp = timestamp;
    }

    public String votoId;

    public Candidato candidato;

    public String timestamp;

    public Voto clone()
    {
        return (Voto)super.clone();
    }

    public static String ice_staticId()
    {
        return "::VotingSystem::Voto";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = 1882148034L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeString(votoId);
        ostr_.writeValue(candidato);
        ostr_.writeString(timestamp);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        votoId = istr_.readString();
        istr_.readValue(v -> candidato = v, Candidato.class);
        timestamp = istr_.readString();
        istr_.endSlice();
    }
}
