//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `VotingService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package VotingSystem;

public class Voto extends com.zeroc.Ice.Value
{
    public Voto()
    {
    }

    public Voto(int id, Candidato candidato)
    {
        this.id = id;
        this.candidato = candidato;
    }

    public int id;

    public Candidato candidato;

    public Voto clone()
    {
        return (Voto)super.clone();
    }

    public static String ice_staticId()
    {
        return "::VotingSystem::Voto";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = -325478967L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeInt(id);
        ostr_.writeValue(candidato);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        id = istr_.readInt();
        istr_.readValue(v -> candidato = v, Candidato.class);
        istr_.endSlice();
    }
}
