# ========================================
# CONFIGURACIÓN DE MESA DE VOTACIÓN
# ========================================

# Identificación de la mesa
node.id=MESA-005
node.nombre=Mesa de Votacion Principal

# Configuración del broker de destino
broker.host=10.147.19.29
broker.puerto=57713
broker.timeout=5000

delta.umbral.votos=50          
# Enviar cada 50 votos
delta.umbral.tiempo=300        
# O cada 0.5 segundos (en ms)

# Thread Pool
threads.pool.size=8

# Configuración de conexión
conexion.reintentos=3
conexion.timeout=3000

# Configuración de logging
logging.nivel=INFO
logging.archivo=mesa-votacion.log
